### ISSUE TITLE
List of supported models and path

### ISSUE THREAD

**Issue by jesuino** [tjake/Jlama#48]
Hello,

Great project, thanks for creating it!

I wanted to know the list of supported models and the path I can use. I tried `google/codegemma-7b`, but I had an error. What are the supported models and what exactly path should I use? 

Here's my code, it works with the default model!

Thanks

https://github.com/jesuino/code-converter/blob/main/code-converter-agent/src/main/java/org/fxapps/codeconverter/service/impl/CodeConverterJLamaService.java

**Comment by tjake** [comment]
Hi, 

Awesome project!

I tried building native and get the following error (jdk21)

```
com.oracle.svm.core.util.UserError$UserException: Discovered unresolved method during parsing: dev.langchain4j.service.AiServiceTokenStream.<init>(java.util.List, dev.langchain4j.service.AiServiceContext, java.lang.Object). This error is reported at image build time because class io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport is registered for linking at image build time by command line and command line.
Error encountered while parsing io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:96)
Parsing context:
   at org.fxapps.codeconverter.service.impl.CodeConverterQuarkusService$$QuarkusImpl.convert(Unknown Source)
   at org.fxapps.codeconverter.CodeConverterCommand.run(CodeConverterCommand.java:53)
   at root method.(Unknown Source)

Detailed message:

        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:814)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Discovered unresolved method during parsing: dev.langchain4j.service.AiServiceTokenStream.<init>(java.util.List, dev.langchain4j.service.AiServiceContext, java.lang.Object). This error is reported at image build time because class io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport is registered for linking at image build time by command line and command line.
Error encountered while parsing io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:96)
Parsing context:
   at org.fxapps.codeconverter.service.impl.CodeConverterQuarkusService$$QuarkusImpl.convert(Unknown Source)
   at org.fxapps.codeconverter.CodeConverterCommand.run(CodeConverterCommand.java:53)
   at root method.(Unknown Source)
```

**Comment by tjake** [comment]
To download the official model you'd need to pass in a HuggingFace auth token to the Jlama model builder.

But I can upload a quantized model for you.  

DeepCoder and codellama will work too.  Also https://huggingface.co/01-ai/Yi-Coder-9B-Chat

**Comment by tjake** [comment]
Actually I guess you don't want the chat model, try https://huggingface.co/01-ai/Yi-Coder-1.5B

**Comment by tjake** [comment]
I ran with codegemma-2b and it works

```
./run-cli.sh complete -p "<|fim_prefix|>public void fibonocci(int n) {<|fim_suffix|><|fim_middle|>" -t 0.3 models/codegemma-2b/

    int a = 0;
    int b = 1;
    int c;
    for (int i = 0; i < n; i++) {
        c = a + b;
        a = b;
        b = c;
        System.out.print(a + " ");
    }
}
```

**Comment by jesuino** [comment]
Hello,

Thanks again for your help. I am trying to use directly in Java because I could not run the CLI. My local build never works (OpenJDK 21 and `mvn clean install` from root dir - [error](https://gist.github.com/jesuino/3e27034e722b1d04f0f7b7cfbdb9616a)), hence why I could not use it yet. 

I tried `Yi-Coder-9B-Chat` and it shows a better error. 
```
Caused by: java.lang.IllegalArgumentException: No tokenizer.json found in /home/..../.jlama/models/Yi-Coder-9B-Chat
```

**Comment by tjake** [comment]
> My local build never works

Yeah sorry this is because it requires a toolchains.xml to be setup for jdk 20/21/22 to build.  I'm going to make the cli downloadable #47 

> No tokenizer.json

Yeah this model doesn't include one in the chat model, just download it from here and put it in the directory listed.  https://huggingface.co/01-ai/Yi-Coder-9B/blob/main/tokenizer.json

**Comment by jesuino** [comment]
Thank you, the model is loaded now. I am having an error, but it is likely not related (see the stack trace below). 

Please let me know if you need help with small fixes. I am not a ML specialist, but I can help with Java

```
Caused by: java.lang.NumberFormatException: For input string: "
	-> 47  		return model.generate(SystemMessage.from(systemMessage)"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:648)
java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 1024
	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:121)
	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:114)
	at com.github.tjake.jlama.model.CausalSelfAttention.forward(CausalSelfAttention.java:206)
	at com.github.tjake.jlama.model.TransformerBlock.forward(TransformerBlock.java:99)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:228)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:201)
	at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:376)
	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:112)
	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:65)
...
```

**Comment by tjake** [comment]
Thank you I'll take a look. In the meantime can you try this one? I know it works https://huggingface.co/tjake/Yi-Coder-1.5B-Chat-Jlama

**Comment by jesuino** [comment]
I had the same error with [tjake/Yi-Coder-1.5B-Chat-Jlama](https://huggingface.co/tjake/Yi-Coder-1.5B-Chat-Jlama):

```
java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 1024
	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:121)
	at com.github.tjake.jlama.tensor.AbstractTensor.slice(AbstractTensor.java:114)
	at com.github.tjake.jlama.model.CausalSelfAttention.forward(CausalSelfAttention.java:206)
	at com.github.tjake.jlama.model.TransformerBlock.forward(TransformerBlock.java:99)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:228)
	at com.github.tjake.jlama.model.AbstractModel.forward(AbstractModel.java:201)
	at com.github.tjake.jlama.model.AbstractModel.generate(AbstractModel.java:376)
	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:112)
	at dev.langchain4j.model.jlama.JlamaChatModel.generate(JlamaChatModel.java:65)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
	at org.fxapps.codeconverter.service.impl.CodeConverterJLamaService.generate(CodeConverterJLamaService.java:47)
```

**Comment by tjake** [comment]
Hmm, what kind of machine cpu do you have?  Can you show me how to run your project without native image?

**Comment by jesuino** [comment]
You can run using `mvn quarkus:dev`. Just rember to use Jlama here:

**Comment by tjake** [comment]
Ah apologies, this is happening because I am cropping the context window to 1024 [here](https://github.com/tjake/Jlama/blob/e0878fb9224ff0879f13419c6e07f241de5150d9/jlama-core/src/main/java/com/github/tjake/jlama/tensor/KvBufferCache.java#L55-L57)

I'll fix this.

**Comment by tjake** [comment]
I've fixed this in #51 and pushing next version to maven repo. Once in you'll need to exclude jlama from langchain4j version and add the new one manually.

**Comment by jesuino** [comment]
THanks for your work on this.

I did try latest model and excluded the dependency from the langchain4j, [see my pom.xml](https://github.com/jesuino/code-converter/blob/main/code-converter-agent/pom.xml#L57)

Now I am having the following error, perhaps I didn't exclude the dependency correctly

``` 
Caused by: java.lang.NoSuchMethodError: 'java.io.File com.github.tjake.jlama.safetensors.SafeTensorSupport.maybeDownloadModel(java.lang.String, java.util.Optional, java.lang.String, java.util.Optional, java.util.Optional, java.util.Optional)'
```

**Comment by tjake** [comment]
Oh shoot I thought I didnt break the api but I did, I'll fix and publish 0.4.1 tonight.  Thanks for being so patient :sweat_smile:

**Comment by tjake** [comment]
Ok `0.4.1` is heading to maven central

**Comment by jesuino** [comment]
Thank you! It works with `0.4.1`!
